# NumPy

The fundamental package for scientific computing with Python

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

Case Studies: __[Image of a Black Hole](https://numpy.org/case-studies/blackhole-image/)__, __[Detection of Gravitational Wave](https://numpy.org/case-studies/gw-discov/)__, __[Sports Analytics](https://numpy.org/case-studies/cricket-analytics/)__, __[Pose Estimation Using Deep Learning](https://numpy.org/case-studies/deeplabcut-dnn/)__

In this tutorial you will learn:

- [How to Create Array](#How-To-Create-Array)
    - [np.array method](#1.-using-np.array-method)
    - [using arange() and linspace()](#2.-Generater-arrays-using-arange()-and-linspace())
    - [Generate arrays using ones or zeros](#3.-Generate-arrays-using-ones-or-zeros)
    - [Generate arrays using random.rand( )](#4.-Generate-arrays-using-random.rand(-))
- [Why Numpy is better than List](#Why-Numpy-and-not-List)
- [Array shape and reshape](#Array-shape-and-reshape)
- [Numpy math](#Numpy-math)
- [Array Broadcasting](#Array-Broadcasting)
- [Questions](#Questions)

In [1]:
import numpy as np

## How to Create Array

### 1. using np.array method

- Ordered collection of elements of basic data types of given length
- Syntax: numpy.array(object)

In [2]:
# using np.array to convert a list to array

array1=np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))
print(array1.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [22]:
array1.shape

(6,)

In [23]:
array1.ndim

1

##### Important Note - 
- Arrray in python is collection of different datatype elements
- All elements are coerced(converted) to same data type i.e conversion will be done of lower datatype elements to higher datatype elements

In [3]:
arr1=np.array([2,3,5.6,'n'])
print(arr1)
print(type(arr1))
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

['2' '3' '5.6' 'n']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [24]:
arr2=np.array([[1, 2, 3.0], [4, 5, 6]])
print(type(arr2))
print(arr2.dtype)
print(arr2.shape)
print(arr2.ndim)

<class 'numpy.ndarray'>
float64
(2, 3)
2


### 2. Generater arrays using arange() and linspace()

numpy.linspace(start, stop, num): Return evenly spaced numbers over a specified interval.
numpy.arange(start, stop, step): Return evenly spaced values within a given interval.

In [11]:
a1 = np.arange(start=10,stop=30,step=3)
print(a1)

[10 13 16 19 22 25 28]


In [ ]:
# Task: Create array of elements between 70 to 50 with 5 difference

In [13]:
np.linspace(20.0, 30.0, num=5)

array([20. , 22.5, 25. , 27.5, 30. ])

### 3. Generate arrays using ones or zeros

In [14]:
print(np.ones(3))

[1. 1. 1.]


In [15]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(np.ones((3, 3),int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
print(np.zeros(3))

[0. 0. 0.]


In [17]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.full((2,2), 7) # Create a constant array

In [18]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 4. Generate arrays using random.rand( )
- numpy.random.rand()- returns an array of given shape filled with random values
- Syntax:numpy.random.rand(shape)
- shape - integer or sequence of integers

In [25]:
#Create 1D array of 5 random numbers between 0 and 1
np.random.rand(5)

array([0.09641187, 0.52112144, 0.88820988, 0.78229578, 0.6329528 ])

In [26]:
#Create 2D array of 35 random numbers between 0 and 1
np.random.rand(7,5)

array([[0.86004372, 0.0849638 , 0.07780084, 0.17197356, 0.27747319],
       [0.93379082, 0.01028457, 0.40576378, 0.36991277, 0.72123398],
       [0.35444982, 0.44037879, 0.2496505 , 0.72139096, 0.32004748],
       [0.40581535, 0.00785078, 0.00276489, 0.3395287 , 0.03615691],
       [0.34279158, 0.15151847, 0.50735565, 0.17756865, 0.63349147],
       [0.43123195, 0.09780607, 0.06167145, 0.4527624 , 0.3179455 ],
       [0.54000771, 0.81573215, 0.99097297, 0.38621757, 0.53750879]])

In [27]:
# Create 2D array of 35 random int elements between 100 to 150
np.random.randint(100,150,(7,5))

array([[131, 123, 138, 148, 132],
       [139, 130, 101, 146, 136],
       [103, 124, 132, 113, 137],
       [109, 115, 139, 141, 127],
       [103, 129, 119, 138, 142],
       [126, 121, 122, 112, 126],
       [101, 100, 123, 125, 102]])

In [28]:
#Sampling over uniform distribution on [0,1)
print(np.random.random(3))

[0.97360656 0.29163634 0.6562037 ]


In [29]:
print(np.random.random((2, 2)))

[[0.3231916  0.23941253]
 [0.40944919 0.69110538]]


In [30]:
#Sampling over standard normal distribution

print(np.random.randn(3,3))

[[ 0.06194779 -1.57325076  0.27736139]
 [ 0.03122204  0.0515224  -1.65136258]
 [-0.4878655   0.50430514 -2.11885567]]


#### Why NumPy and not list

1. Speed - Array is faster than list
2. Memory Storage - Array takes less memory than list

In [6]:
import time
# Consider case for List
py_list=[i for i in range(100000)]
start=time.time()
py_list=[i+4 for i in py_list]
stop=time.time()
print(stop-start)

0.006520748138427734


In [8]:
# Consider case for Numpy Array

py_arr=np.array([i for i in range(1000000)])
start=time.time()
py_arr=py_arr+4
stop=time.time()
print(stop-start)

0.0017671585083007812


In [9]:
import sys
a1=np.arange(100)
print(type(a1))
print(a1.size)
print("Total space taken by a1 is",a1.itemsize*100)

<class 'numpy.ndarray'>
100
Total space taken by a1 is 400


In [10]:
l1=[i for i in range(100)]
print("Total size taken by l1 =",sys.getsizeof(l1[0])*len(l1))

Total size taken by l1 = 2400


## Array shape and reshape

In [34]:
array_2d=np.array([[1,2,3,4],[6,7,8,9]])
print(array_2d)
print(array_2d.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


In [36]:
array_2d.reshape(4,2)

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [35]:
array_2d.reshape(1,8)

array([[1, 2, 3, 4, 6, 7, 8, 9]])

In [37]:
array_1d = np.array([1, 2, 3, 4])
array_1d.shape

(4,)

In [38]:
array_1d.reshape(-1, 4)

array([[1, 2, 3, 4]])

In [39]:
print(array_1d.reshape(-1, 4).shape)

(1, 4)


In [41]:
print(array_1d.size)

4


In [42]:
create_array = np.array([i for i in range(400)])
new_array = create_array.reshape((20, 20))

print(new_array[:, 5])

[  5  25  45  65  85 105 125 145 165 185 205 225 245 265 285 305 325 345
 365 385]


In [43]:
sample_3d_array = np.array([i for i in range(1000)])
sample_3d_array = sample_3d_array.reshape((10, 10, 10))

In [44]:
print(sample_3d_array[:,1,1])

[ 11 111 211 311 411 511 611 711 811 911]


In [46]:
print(sample_3d_array[2, :, 1])

[201 211 221 231 241 251 261 271 281 291]


In [47]:
print(sample_3d_array[2, 3, :])

[230 231 232 233 234 235 236 237 238 239]


In [48]:
print(sample_3d_array[1, :, :])

[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [50]:
a1 = np.arange(4)
a1

array([0, 1, 2, 3])

In [52]:
print(np.reshape(a1,(2,2), order = 'C'))

[[0 1]
 [2 3]]


In [53]:
print(np.reshape(a1,(2,2), order = 'F'))

[[0 2]
 [1 3]]


## Numpy math

In [54]:
a1 = np.array([10,20,30,40])

# element wise operations!!

print(a1 + 5)
print(a1 * 5)
print(np.sqrt(a1))
print(np.power(a1, 2))
print(np.exp(a1))
print(np.log(a1))

[15 25 35 45]
[ 50 100 150 200]
[3.16227766 4.47213595 5.47722558 6.32455532]
[ 100  400  900 1600]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
[2.30258509 2.99573227 3.40119738 3.68887945]


In [56]:
a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a_2d)
print(f'shape={a_2d.shape}')
print(np.sum(a_2d))
print(np.sum(a_2d, axis=0))
print(np.sum(a_2d, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape=(3, 3)
45
[12 15 18]
[ 6 15 24]


In [57]:
a_3d = np.array([i for i in range(27)]).reshape((3, 3, 3))
print(a_3d)

print(np.sum(a_3d, axis=0))
print(np.sum(a_3d, axis=1))
print(np.sum(a_3d, axis=(1, 2)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
[ 36 117 198]


In [59]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
print(a1*a2) #element wise multiplication

[ 5 12 21 32]


In [60]:
print(np.multiply(a1,a2))

[ 5 12 21 32]


In [61]:
print(a2.shape)
print(a2.reshape(4,-1).shape)

(4,)
(4, 1)


In [63]:
a2.reshape(4,-1)

array([[5],
       [6],
       [7],
       [8]])

In [62]:
print(a1 * a2.reshape(4,-1))

[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


Doing Dot product in multiple ways

In [64]:
a1.dot(a2)

70

In [65]:
np.sum(a1*a2)

70

In [66]:
a1 @ a2 # similar to np.matmul(a1,a2)

70

In [69]:
a1.dot(a2.T)

70

In [71]:
# Check for 2d arrays

mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
np.matmul(mat1, mat2)

array([[19, 22],
       [43, 50]])

In [73]:
np.multiply(mat1,mat2)

array([[ 5, 12],
       [21, 32]])

Note np.multiply is element-wise multiplication, not proper matrix multiplication

we use matmul for 2D matrix multiplication. For dim>3, Numpy treats them as a stack of matrices. See __[Documentation on matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)__

## Array Broadcasting 

Numpy has capability to perform operations on arrays with different shapes, inferring/expanding dimension as needed. Taking examples from [Scipy's documentaiton on numpy](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html), some examples can be 

```
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4


A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

Essentially all dimensions of size 1 can be "over-looked" or "expanded" to match dimension from another operator. But the order of such must be matched. Dimension of size 1 is only prepended, not appended. For example, the following would not work, though you might think we can add another dimension at the end of B.

```
A      (3d array):  15 x 3 x 5
B      (2d array):       1 x 3
Result (3d array):  15 x 3 x 5
```

In [75]:
a1 = np.array([i for i in range(9)]).reshape(3, 3)
a2 = np.array([[1, 2, 3]])
a3 = np.array([1, 2, 3])

print(a1)
print()
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 2 3]]


In [77]:
print(a1.shape)
print()
print(a2.shape)

(3, 3)

(1, 3)


In [78]:
print(a1+a2)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [79]:
print(a2.T.shape)

(3, 1)


In [80]:
a1 + a2.T

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

Broadcasting won't work in the case for 3 $\times$ 5 $\times$ 2 with 1 $\times$ 5. 

It will work for 3 $\times$ 5 $\times$ 2 with 5 $\times$ 1

In [86]:
mat1 = np.array([i for i in range(30)]).reshape(3,5,2)
mat2 = np.array([[1,2,3,4,5]])
print(mat1.shape)
print()
print(mat2.shape)

(3, 5, 2)

(1, 5)


In [82]:
print(mat1 + mat2)

ValueError: operands could not be broadcast together with shapes (10,5,2) (1,5) 

In [87]:
print(mat2.T.shape)

(5, 1)


In [88]:
print(mat1 + mat2.T)

[[[ 1  2]
  [ 4  5]
  [ 7  8]
  [10 11]
  [13 14]]

 [[11 12]
  [14 15]
  [17 18]
  [20 21]
  [23 24]]

 [[21 22]
  [24 25]
  [27 28]
  [30 31]
  [33 34]]]


## Questions

1.  Find the dot product of the matrix with any matix. Print the size/shape of the matrix

2.  Reverse a numpy array

3.  Write a NumPy program to create a 5x5 identity matrix and stack it vertically and horizontally.

4. Write a NumPy program to create a 4x4 array with random values and subtract the mean of each column from each element.